version: '1'

services:
  traefik:
    restart: always
    image: traefik:2.3
    command: --api.insecure=true --providers.docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.ginge.localhost`)"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik:/etc/traefik
      - ./.certs:/.certs
    networks:
      - traefik
  local-mysql:
    restart: always
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
        - local-mysql
volumes:
  mysql-data:
networks:
  local-mysql:
    external: true
  traefik:
    external: true