global:
  checkNewVersion: true
  sendAnonymousUsage: false
ping: {}
log: {}
api:
  dashboard: true
  insecure: true
providers:
  docker:
    defaultRule: 'Host(`{{ normalize .Name }}.ginge.localhost`)'
    exposedByDefault: false
    network: traefik
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'