version: "3.7"
   
services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    working_dir: /usr/src/app
    command: | 
      bundle exec jekyll serve
      --host 0.0.0.0
      --livereload
      --livereload-port 4001
    volumes:
      - .:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jekyll.loadbalancer.server.port=4000"
      - "traefik.http.routers.jekyll.rule=Host(`jekyll.ginge.localhost`)"
    networks:
      - internal
      - traefik
    restart: on-failure
    ports:
      - 4000:4000
      - 4001:4001


  assets:
    build: 
      context: .
      dockerfile: node.dockerfile
    restart: on-failure
    working_dir: /node
    volumes:
      - .:/node
    command: npm run watch
    networks:
      - internal
    ports:
      - 3000:3000
      - 3001:3001

networks:
  internal:
  traefik:
    external: true